(* Pickle opcode bytes.

   Names and codes are taken verbatim from CPython's
   [modules/cpython/Lib/pickletools.py] opcode table.  The comment after each
   constant records the protocol version that introduced it. *)

(* Integers, booleans, None *)
let int = 'I' (* proto 0 *)
let binint = 'J' (* proto 1 *)
let binint1 = 'K' (* proto 1 *)
let binint2 = 'M' (* proto 1 *)
let long = 'L' (* proto 0 *)
let long1 = '\x8a' (* proto 2 *)
let long4 = '\x8b' (* proto 2 *)
let none = 'N' (* proto 0 *)
let newtrue = '\x88' (* proto 2 *)
let newfalse = '\x89' (* proto 2 *)

(* Floats *)
let float = 'F' (* proto 0 *)
let binfloat = 'G' (* proto 1 *)

(* Strings / bytes *)
let string = 'S' (* proto 0 *)
let binstring = 'T' (* proto 1 *)
let short_binstring = 'U' (* proto 1 *)
let binbytes = 'B' (* proto 3 *)
let short_binbytes = 'C' (* proto 3 *)
let binbytes8 = '\x8e' (* proto 4 *)
let bytearray8 = '\x96' (* proto 5 *)
let next_buffer = '\x97' (* proto 5 *)
let readonly_buffer = '\x98' (* proto 5 *)
let unicode = 'V' (* proto 0 *)
let short_binunicode = '\x8c' (* proto 4 *)
let binunicode = 'X' (* proto 1 *)
let binunicode8 = '\x8d' (* proto 4 *)

(* Lists *)
let empty_list = ']' (* proto 1 *)
let append = 'a' (* proto 0 *)
let appends = 'e' (* proto 1 *)
let list = 'l' (* proto 0 *)

(* Tuples *)
let empty_tuple = ')' (* proto 1 *)
let tuple = 't' (* proto 0 *)
let tuple1 = '\x85' (* proto 2 *)
let tuple2 = '\x86' (* proto 2 *)
let tuple3 = '\x87' (* proto 2 *)

(* Dicts *)
let empty_dict = '}' (* proto 1 *)
let dict = 'd' (* proto 0 *)
let setitem = 's' (* proto 0 *)
let setitems = 'u' (* proto 1 *)

(* Sets *)
let empty_set = '\x8f' (* proto 4 *)
let additems = '\x90' (* proto 4 *)
let frozenset = '\x91' (* proto 4 *)

(* Stack manipulation *)
let pop = '0' (* proto 0 *)
let dup = '2' (* proto 0 *)
let mark = '(' (* proto 0 *)
let pop_mark = '1' (* proto 1 *)

(* Memo *)
let get = 'g' (* proto 0 *)
let binget = 'h' (* proto 1 *)
let long_binget = 'j' (* proto 1 *)
let put = 'p' (* proto 0 *)
let binput = 'q' (* proto 1 *)
let long_binput = 'r' (* proto 1 *)
let memoize = '\x94' (* proto 4 *)

(* Extension registry *)
let ext1 = '\x82' (* proto 2 *)
let ext2 = '\x83' (* proto 2 *)
let ext4 = '\x84' (* proto 2 *)

(* Globals / object construction / reduce *)
let global = 'c' (* proto 0 *)
let stack_global = '\x93' (* proto 4 *)
let reduce = 'R' (* proto 0 *)
let build = 'b' (* proto 0 *)
let inst = 'i' (* proto 0 *)
let obj = 'o' (* proto 1 *)
let newobj = '\x81' (* proto 2 *)
let newobj_ex = '\x92' (* proto 4 *)

(* Framing / protocol *)
let proto = '\x80' (* proto 2 *)
let stop = '.' (* proto 0 *)
let frame = '\x95' (* proto 4 *)

(* Persistent ids *)
let persid = 'P' (* proto 0 *)
let binpersid = 'Q' (* proto 1 *)
